Repository the-collab-lab/tcl-66-smart-shopping-list, pull requests merged in 2024-03, with the labels that each got.

#31 #28 [BUG]: AddList handleSubmit is synchronous but contains an unresolved Promise
  src/api/firebase.js
  src/components/AddList.jsx
Labels: bug fix

#32 10. As a user, I want to be alerted when I’m entering an empty item or an item that's already on my list
  src/App.jsx
  src/api/firebase.js
  src/components/AddItem.jsx
  src/components/AddList.jsx
  src/views/List.jsx
  src/views/ManageList.jsx
Labels: enhancement

#33 11. As an item, I want my estimated next purchase date to be computed at the time my purchase is recorded in the database, so the app can learn how often I buy different items
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/ListItem.jsx
  src/views/List.jsx
Labels: enhancement

#36 12. As a user, I want to be able to delete items from my shopping list so that my list isn’t cluttered with items I don’t want to buy in the future.
  src/api/firebase.js
  src/components/ListItem.jsx
Labels: enhancement

#37 13. As a user, I want to view a list of my shopping list items in order of how soon I am likely to need to buy each of them again so that it’s clear what I need to buy soon
  src/api/firebase.js
  src/components/ListItem.jsx
  src/utils/dates.js
  src/utils/helpers.js
  src/views/List.jsx
Labels: accessibility, enhancement

#34 Uncheck feature
  src/api/firebase.js
  src/components/AddItem.jsx
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/utils/dates.js
  src/utils/helpers.js
  src/views/List.jsx
Labels: enhancement

#40 16. Layout Changes and Tailwind Implementation
  PROJECT-BRIEF.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/api/useAuth.jsx
  src/components/AddItem.jsx
  src/components/AddList.jsx
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/components/SingleList.css
  src/components/SingleList.jsx
  src/index.css
  src/utils/helpers.js
  src/views/Home.css
  src/views/Home.jsx
  src/views/Layout.css
  src/views/Layout.jsx
  src/views/List.jsx
  tailwind.config.js
Labels: accessibility, enhancement, refactoring

#42 17. As a user I want my lists protected by google and firebase authentication. I want the log in/ sign up to be separated from the rest of the app for clarity and protection/privacy.
  src/App.jsx
  src/api/useAuth.jsx
  src/assets/GoogleIcon.jsx
  src/assets/Logo.jsx
  src/assets/contrastGraph.png
  src/assets/graph.png
  src/assets/lightContrastGraph.png
  src/assets/lightestContrastGraph.png
  src/components/PrivateRoute.jsx
  src/components/PublicRoute.jsx
  src/components/Spinner.jsx
  src/components/index.js
  src/views/Err.jsx
  src/views/List.jsx
  src/views/Login.jsx
  src/views/index.js
  tailwind.config.js
Labels: accessibility, enhancement, security

#44 15. Create reusable components
  src/components/AddItem.jsx
  src/components/Button.jsx
  src/components/ListItem.jsx
  src/components/SelectInput.jsx
  src/components/TextInput.jsx
  src/components/Urgency.jsx
  src/utils/helpers.js
  src/views/List.jsx
  src/views/Login.jsx
  tailwind.config.js
Labels: enhancement

#47 issue-20[BUG-FIX]
  src/App.jsx
  src/api/useAuth.jsx
Labels: bug fix

#52 23. Delete List Feature
  src/api/firebase.js
  src/components/AddList.jsx
  src/components/SingleList.jsx
  src/views/Home.jsx
Labels: enhancement

#50 21. Share/Unshare Feature
  package-lock.json
  package.json
  src/App.jsx
  src/api/firebase.js
  src/components/AddItem.jsx
  src/components/AddList.jsx
  src/components/Button.jsx
  src/components/InviteForm.jsx
  src/components/ListItem.jsx
  src/components/Modal.jsx
  src/components/SelectInput.jsx
  src/components/SharedWithList.jsx
  src/components/Urgency.jsx
  src/utils/capitalize.js
  src/utils/index.js
  src/views/Layout.jsx
  src/views/List.jsx
  src/views/ManageList.jsx
Labels: enhancement
