Repository the-collab-lab/tcl-66-smart-shopping-list, pull requests merged in 2024-04, with the labels that each got.

#56 24. When the user refreshes or navigates around the app, the login page should not flash on the screen. An indictor should show the user that something is happening during wait times. #54
  src/App.jsx
  src/api/useAuth.jsx
  src/components/PrivateRoute.jsx
  src/components/PublicRoute.jsx
  src/components/SingleList.jsx
  src/views/Err.jsx
  src/views/Home.jsx
  src/views/Layout.jsx
  src/views/List.jsx
  src/views/Login.jsx
Labels: enhancement

#58 25. Make app more responsive for mobile compatibility
  src/components/AddItem.jsx
  src/components/AddList.jsx
  src/components/NavigationBar.jsx
  src/components/NavigationBarAddList.jsx
  src/components/NavigationBarModal.jsx
  src/components/NavigationBarSingleList.jsx
  src/components/SingleList.jsx
  src/views/Layout.jsx
  src/views/List.jsx
Labels: accessibility, enhancement

#60 Ec issue #29 bug fix - Lists in the Nav Bar throw error when local storage is empty
  src/components/NavigationBarSingleList.jsx
Labels: bug fix

#63 Nav Padding fix
  src/components/NavigationBar.jsx
  src/components/NavigationBarSingleList.jsx
Labels: enhancement
